name: Docker Build & Push

on:
  push:
    tags:
      - "*"
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

env:
  DOCKER_USERNAME: ausfestivus
  DOCKER_CONTAINER_NAME: docker-caddy-azuredns
  DOCKER_TARGET_PLATFORM: linux/amd64, linux/arm64, linux/arm/v8, linux/arm/v7
  GITHUB_REGISTRY_ORG_NAME: best-family

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ env.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Login to Quay Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: quay.io
      #     username: ${{ env.DOCKER_USERNAME }}+pushbot
      #     password: ${{ secrets.QUAY_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        if: success()
        id: meta
        uses: docker/metadata-action@6d6eaf34518db036006be0b031c21fd4eb72ef69
        with:
          images: |
            ghcr.io/${{ github.repository }}

      - name: Build and push Docker images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
