name: validate-codeowners
run-name: ${{ github.actor }} is validating CODEOWNERS

on: [push]

jobs:
    validate-codeowners:
        runs-on: ubuntu-latest
        steps:
            # Checks-out your repository, which is validated in the next step
            - uses: actions/checkout@v2
            - uses: mszostok/codeowners-validator@v0.7.4
              with:
                checks: "files,owners,duppatterns,syntax"
                experimental_checks: "notowned,avoid-shadowing"
                # GitHub access token is required only if the `owners` check is enabled
                github_access_token: "${{ secrets.OWNERS_VALIDATOR_GITHUB_SECRET }}"
